site_name: Ender-3
copyright: Copyright &copy; 2023 Ender 3 Russian Community
theme:
  name: material
  language: ru
  favicon: images/favicon.png
  logo: images/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/ender_3
nav:
  - Домашняя страница: index.md
extra_css:
  - stylesheets/extra.css
